# Generated by Django 4.2.10 on 2024-05-12 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='заголовок')),
                ('image', models.ImageField(upload_to='image/galery', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'db_table': 'galery_table',
            },
        ),
        migrations.CreateModel(
            name='TravelSpots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=40, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='image/travel_spots', verbose_name='изображение')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('in_uzbekistan', models.BooleanField(default=True, verbose_name='в узбекистане')),
            ],
            options={
                'verbose_name': 'Место для путешествий',
                'verbose_name_plural': 'Места для путешествий',
                'db_table': 'travel_spot',
            },
        ),
    ]
