# Generated by Django 4.2.10 on 2024-05-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='galery',
            name='title_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='travelspots',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travelspots',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travelspots',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='travelspots',
            name='title_uz',
            field=models.CharField(max_length=40, null=True, verbose_name='Адрес'),
        ),
    ]
