# Generated by Django 4.2.10 on 2024-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_travelspots_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspots',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
