# Generated by Django 4.2.10 on 2024-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_travelspots_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelspots',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
