# Generated by Django 4.2.10 on 2024-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_travelspots_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspots',
            name='slug_ru',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='travelspots',
            name='slug_uz',
            field=models.SlugField(null=True),
        ),
    ]
