# Generated by Django 4.2.10 on 2024-05-29 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_travelspots_slug_ru_travelspots_slug_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galery',
            old_name='title_uz',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='travelspots',
            old_name='description_uz',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='travelspots',
            old_name='title_uz',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='travelspots',
            name='id',
        ),
        migrations.RemoveField(
            model_name='travelspots',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='travelspots',
            name='slug_uz',
        ),
        migrations.AlterField(
            model_name='travelspots',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelspots',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
