# Generated by Django 4.2.10 on 2024-05-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='tags',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название тегов'),
        ),
        migrations.AddField(
            model_name='tags',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название тегов'),
        ),
    ]
