# Generated by Django 4.2.10 on 2024-05-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_service', '0002_news_content_ru_news_content_uz_news_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_uz',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
