# Generated by Django 4.2.10 on 2024-05-20 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('press_service', '0003_remove_news_content_ru_remove_news_content_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
