# Generated by Django 4.2.10 on 2024-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_service', '0006_news_title_ru_news_title_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
