# Generated by Django 4.2.10 on 2024-05-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_service', '0007_news_content_ru_news_content_uz_news_slug_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content_uz',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_uz',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug_uz',
        ),
    ]
