# Generated by Django 4.2.10 on 2024-05-12 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Подписаться',
                'verbose_name_plural': 'Подписаться',
                'db_table': 'subscribe',
                'indexes': [models.Index(fields=['username'], name='subscribe_usernam_7802c5_idx')],
            },
        ),
    ]
