# Generated by Django 4.2.10 on 2024-05-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_usersubscribetion_usersubscription_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
