# Generated by Django 4.2.10 on 2024-05-29 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='id',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
