# Generated by Django 4.2.10 on 2024-07-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests', models.JSONField()),
                ('language', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('residency', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerOrderId',
            fields=[
                ('partner_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirCityCodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('airport', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'airport_code_list',
                'verbose_name_plural': 'airport_code_list',
                'db_table': 'airport_code_list',
                'indexes': [models.Index(fields=['country', 'airport', 'code'], name='airport_cod_country_f63421_idx')],
            },
        ),
    ]
