# Generated by Django 4.2.10 on 2024-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests', models.JSONField()),
                ('language', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('residency', models.CharField(max_length=2)),
            ],
        ),
    ]
