# Generated by Django 4.2.10 on 2024-06-14 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCityCodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('airport', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'airport_code_list',
                'verbose_name_plural': 'airport_code_list',
                'db_table': 'airport_code_list',
                'indexes': [models.Index(fields=['country', 'airport', 'code'], name='airport_cod_country_f63421_idx')],
            },
        ),
    ]
