# Generated by Django 4.2.10 on 2024-08-27 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_api', '0002_airport_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTicketOrderhistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Статус авиабилета',
                'verbose_name_plural': 'Статус авиабилета',
            },
        ),
        migrations.RemoveField(
            model_name='airtickethistory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='airticketstatustoken',
            options={'verbose_name': 'Статус авиабилета', 'verbose_name_plural': 'Статус авиабилета'},
        ),
        migrations.AlterModelOptions(
            name='clientspentdeposit',
            options={'verbose_name': 'Депозит, потраченный клиентом', 'verbose_name_plural': 'Депозит, потраченный клиентом'},
        ),
        migrations.AlterModelOptions(
            name='hotelorderhistory',
            options={'verbose_name': 'История заказов в отеле', 'verbose_name_plural': 'История заказов в отеле'},
        ),
        migrations.RenameIndex(
            model_name='aircitycodes',
            new_name='external_ap_country_39fbec_idx',
            old_name='airport_cod_country_f63421_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdeposit',
            new_name='external_ap_user_id_07163e_idx',
            old_name='client_bala_user_id_6064d9_idx',
        ),
        migrations.RenameIndex(
            model_name='clientspentdeposit',
            new_name='external_ap_user_id_7d7b63_idx',
            old_name='client_spen_user_id_b0578f_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerorderid',
            new_name='external_ap_partner_7d4913_idx',
            old_name='partner_ord_partner_db2f2c_idx',
        ),
        migrations.RemoveField(
            model_name='clientdeposit',
            name='amout',
        ),
        migrations.RemoveField(
            model_name='clientspentdeposit',
            name='amout',
        ),
        migrations.AddField(
            model_name='clientdeposit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='clientdeposit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка '),
        ),
        migrations.AddField(
            model_name='clientspentdeposit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='clientspentdeposit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка '),
        ),
        migrations.AddField(
            model_name='hotelorderhistory',
            name='hotel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerorderid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='airticketstatustoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdeposit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='clientspentdeposit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='hotelorderhistory',
            index=models.Index(fields=['order_id', 'id'], name='external_ap_order_i_813e8d_idx'),
        ),
        migrations.AlterModelTable(
            name='aircitycodes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clientdeposit',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clientspentdeposit',
            table=None,
        ),
        migrations.AlterModelTable(
            name='partnerorderid',
            table=None,
        ),
        migrations.DeleteModel(
            name='AirticketHistory',
        ),
    ]
