# Generated by Django 4.2.10 on 2024-09-05 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_api', '0003_airticketorderhistory_remove_airtickethistory_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airticketorderhistory',
            options={'verbose_name': 'История заказов в авиабилета', 'verbose_name_plural': 'История заказов в авиабилета'},
        ),
        migrations.RemoveField(
            model_name='hotelorderhistory',
            name='guest_full_name',
        ),
        migrations.RemoveField(
            model_name='hotelorderhistory',
            name='order_status',
        ),
        migrations.AddField(
            model_name='airticketorderhistory',
            name='fligths_group',
            field=models.JSONField(blank=True, null=True, verbose_name='группа полетов'),
        ),
        migrations.AddField(
            model_name='airticketorderhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='hotelorderhistory',
            name='guests',
            field=models.JSONField(blank=True, null=True, verbose_name='Полное имя гостя'),
        ),
        migrations.AddField(
            model_name='partnerorderid',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор товара'),
        ),
        migrations.AlterField(
            model_name='airticketstatustoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='airticketstatustoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='clientdeposit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='clientspentdeposit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='check_in',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Регистрироваться'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='check_out',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Проверить'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='free_cancelation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бесплатная отмена'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='hotel_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор отеля'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='order_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор заказа'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название комнаты'),
        ),
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='partnerorderid',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор заказа'),
        ),
        migrations.AlterField(
            model_name='partnerorderid',
            name='partner_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор заказа партнера'),
        ),
    ]
