# Generated by Django 4.2.10 on 2024-08-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_api', '0005_airticketorderhistory_location_begin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='location_begin',
        ),
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='location_end',
        ),
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='hotelorderhistory',
            name='order_status',
        ),
        migrations.AddField(
            model_name='airticketorderhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
