# Generated by Django 4.2.10 on 2024-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0006_remove_airticketorderhistory_location_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airticketorderhistory',
            name='carrier',
            field=models.JSONField(blank=True, null=True, verbose_name='carrier'),
        ),
        migrations.AddField(
            model_name='airticketorderhistory',
            name='fare_seats',
            field=models.JSONField(blank=True, null=True, verbose_name='fare_seats'),
        ),
        migrations.AddField(
            model_name='airticketorderhistory',
            name='fare_total',
            field=models.JSONField(blank=True, null=True, verbose_name='fare_total'),
        ),
        migrations.AddField(
            model_name='airticketorderhistory',
            name='segments',
            field=models.JSONField(blank=True, null=True, verbose_name='segments'),
        ),
    ]
