# Generated by Django 4.2.10 on 2024-09-27 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0007_airticketorderhistory_token_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorderhistory',
            name='partner_order_id',
            field=models.CharField(default=datetime.datetime(2024, 9, 27, 10, 41, 38, 842818, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='Идентификатор заказа партнера'),
            preserve_default=False,
        ),
    ]
