# Generated by Django 4.2.10 on 2024-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0007_airticketorderhistory_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelorderhistory',
            name='guest_full_name',
        ),
        migrations.AddField(
            model_name='hotelorderhistory',
            name='guests',
            field=models.JSONField(blank=True, null=True, verbose_name='Полное имя гостя'),
        ),
    ]
