# Generated by Django 4.2.10 on 2024-08-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0008_remove_hotelorderhistory_guest_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='fare_seats',
        ),
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='fare_total',
        ),
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='airticketorderhistory',
            name='travel_duration',
        ),
        migrations.AddField(
            model_name='airticketorderhistory',
            name='flights_group',
            field=models.JSONField(blank=True, null=True, verbose_name=''),
        ),
    ]
