name: Production deploy Totrans

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET_FOLDER: "/root/projects/creativetg"

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: GIT pulling from github repository
      run: |
        scp -P ${{ secrets.SSH_PORT }} -r . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ env.TARGET_FOLDER }}

    - name: Command using from script
      run: |
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          git --work-tree="${{ env.TARGET_FOLDER }}" --git-dir="${{ env.TARGET_FOLDER }}/.git" clean -f .
          /root/projects/creativetg/venv/bin/pip install -r /root/projects/creativetg/create_travel/requirements.txt
          /root/projects/creativetg/venv/bin/python /root/projects/creativetg/create_travel/src/manage.py migrate
          sudo systemctl restart creativetg.service
        EOF
